lxc-centos: update template for centos5

diff --git a/templates/lxc-centos.in b/templates/lxc-centos.in
--- a/templates/lxc-centos.in
+++ b/templates/lxc-centos.in
@@ -90,6 +90,18 @@ pre-start script
         exit 0;
 end script
 EOF
+    elif [ "$release" = "5" ]; then 
+        cat <<EOF > $rootfs_path/etc/rc.d/lxc.sysinit
+#! /bin/bash
+rm -f /etc/mtab /var/run/*.{pid,lock} /var/lock/subsys/*
+rm -rf {/,/var}/tmp/* 
+echo "/dev/root               /                       rootfs   defaults        0 0" > /etc/mtab
+exit 0
+EOF
+        chmod 755 $rootfs_path/etc/rc.d/lxc.sysinit
+        sed -i 's|si::sysinit:/etc/rc.d/rc.sysinit|si::bootwait:/etc/rc.d/lxc.sysinit|'  $rootfs_path/etc/inittab
+        sed -i 's|^1:|co:2345:respawn:/sbin/mingetty console\n1:|' $rootfs_path/etc/inittab
+        sed -i 's|^\([56]:\)|#\1|' $rootfs_path/etc/inittab
     fi
 
     dev_path="${rootfs_path}/dev"
@@ -171,6 +183,30 @@ EOF
 
     # use same nameservers as hosts, needed for "yum update later"
     cp -a /etc/resolv.conf $INSTALL_ROOT/etc/
+
+    # need to redo the process for centos5 using the newly-installed yum
+    # due to rpmdb version difference
+    if [ "$release" = "5" ]; then
+        mv $REPO_FILE $REPO_FILE.tmp
+        mkdir $INSTALL_ROOT/etc/yum.repos.disabled
+        mv $INSTALL_ROOT/etc/yum.repos.d/*.repo $INSTALL_ROOT/etc/yum.repos.disabled/
+        mv $REPO_FILE.tmp $REPO_FILE
+        mkdir -p $INSTALL_ROOT/$INSTALL_ROOT/etc
+        cp -a /etc/resolv.conf $INSTALL_ROOT/$INSTALL_ROOT/etc/
+        mkdir -p $INSTALL_ROOT/$INSTALL_ROOT/dev
+        mknod -m 666 $INSTALL_ROOT/$INSTALL_ROOT/dev/null c 1 3
+        mknod -m 666 $INSTALL_ROOT/$INSTALL_ROOT/dev/urandom c 1 9
+        mkdir -p $INSTALL_ROOT/$INSTALL_ROOT/var/cache/yum
+        cp -al $INSTALL_ROOT/var/cache/yum/* $INSTALL_ROOT/$INSTALL_ROOT/var/cache/yum/
+        chroot $INSTALL_ROOT $YUM install $PKG_LIST
+        if [ $? -ne 0 ]; then
+            echo "Failed to download the rootfs, aborting."
+            return 1
+        fi
+        mv $INSTALL_ROOT/$INSTALL_ROOT $INSTALL_ROOT.tmp
+        rm -rf $INSTALL_ROOT
+        mv $INSTALL_ROOT.tmp $INSTALL_ROOT
+    fi
 
     rm -f $REPO_FILE
     $YUM clean packages
